- build.sh
When using a git version lower than 3.0 , 
the command  ”git branch --show-current“   under build.sh will report an error  like inssue: https://github.com/flomesh-io/pipy/issues/23
So, replace it with another command to implement similar functionality
> fix: git branch --show-current

- generate_version_h.sh
- src/pjs/types.hpp
- Fixes issues where code compiled with clang13 in release mode was segfaulting
- updated `generate_version_h.sh` to retrieve version info from local git repo, previously it was hard-coded as "0.0.0"
> Fixes Clang13 sigsev issue

- CMakeLists.txt
- cmake/c++-standards.cmake
- cmake/compiler-options.cmake
- cmake/link-time-optimization.cmake
- cmake/sanitizers.cmake
- Bumped CMake minimum required version to `3.10`
- Added cmake modules (details) below
- enforced `C++ 11` version requirement
- enabled LTO/IPO (which will work when compiled using clang)
- added enabling sanitizers (Address, Memory, MemoryWithOrigins, Thread, Undefined , Leak) support (details below)
- added compile time options support 
Using the functions `cxx_11()`, `cxx_14()`, `cxx_17()` or `cxx_20()` this adds the appropriate flags for both unix and MSVC compilers, even for those before 3.11 with improper support.
These obviously force the standard to be required, and also disables compiler-specific extensions, ie `--std=gnu++11`. This helps to prevent fragmenting the code base with items not available elsewhere, adhering to the agreed C++ standards only.
There are two callable …
> Updated cmake version and added modules

- CMakeLists.txt
- docs/reference/api/Configuration/compressHTTP.mdx
- docs/reference/api/Configuration/compresssMessage.mdx
- src/api/configuration.cpp
- src/api/configuration.hpp
- src/compress.cpp
- src/compress.hpp
- src/filters/compress-message.cpp
- src/filters/compress-message.hpp
Added support for HTTP response compression and this PR adds two filters `compressHTTP` and `compressMessage`. Both of these filters are configurable via `options` object. Documentation for these two filters is added as well.
There are options you can use in the _options_ parameter to configure compression method, compression level:
- _enabled_ - Toggle compression mode. Boolean flag either `true` or `false`. default is _true_.
- _method_ - Compression method to use. It need to be one of `deflate`, `gzip`, and `brotli`. default is _gzip_.
- _level_  - Compression level settings. It need to be one of `default`, `none`, `speed`, `best`. default is _default_.
> Added compressHTTP & compressMessage filters

- CMakeLists.txt
* Disabled brotli tests
* Enabled brotli bundled mode
* Fixed openssl build path issue that was occurring on running clean and then make.
> Updated CMakeLists to disable brotli tests, fixed openssl path issue

- .github/workflows/ci.yaml
The previous CI changes cause the general nightly build failed to upload artifacts, so move pipy-repo to independent flow.
> [ci] change pipy repo build flow

- .github/workflows/ci.yaml
No need to build pipy-repo at this stage, and we move it to the steps after 'save log'
> [ci] move pipy-repo build to subsequent step

- Dockerfile
- docker-entrypoint.sh
Currently we only start one pipy instance in sidecar, this change allow container start multiple pipy instance based on the CPU limit.
> [docker] start multiple pipy instances based on docker cpu quota

- src/filters/http2.cpp
Fixed http2 stream bug, avoid multiple set_pending on Endpoint::StreamBase.
> Avoid multiple set_pending on Endpoint::StreamBase.

- build.sh
there are 3 dictionaries packaged into the tar file accidentally, fix it and add binary only.
```
a .
a ./usr
a ./usr/local
a ./usr/local/bin
```
> [fix] package binary only, without the dictionaries

- Dockerfile
* Bump base image version to alpine:3.16.1, which fix the CVE-2022-2097
* Do not install node if PIPY_GUI is OFF
* Use the latest node version(`16.16.0-r0`) in the alpine repo
> [ci] fix node version issue

- src/filters/mux.cpp
Avoid selecting sessions that are about to close.
> Avoid selecting sessions that are about to close.

- rpm/pipy.spec
as llvm-toolset-7.0-clang does not provide clang, let's BuildRequires it directly.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
1. We prefer to discuss the underlying issue _prior_ to discussing the code. Therefore, we kindly ask you to refer to an existing issue, or an existing discussion in a public space with members of the Core Team. In few cases, we acknowledge that this might not be necessary, for instance when refactoring code or small bug fixes. In this case, the PR must include the same information …
> [ci]: use llvm-toolset-7.0-clang instead of clang on el7

- rpm/Dockerfile
- rpm/pipy.spec
so we can install nodejs only if `--with gui` is passed to rpmbuild.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
1. We prefer to discuss the underlying issue _prior_ to discussing the code. Therefore, we kindly ask you to refer to an existing issue, or an existing discussion in a public space with members of the Core Team. In few cases, we acknowledge that this might not be necessary, for instance when refactoring code or small bug fixes. In this case, the PR must include the same information an issue would …
> [ci] add rpmbuild option of --with gui

- CMakeLists.txt
-Wdelete-non-abstract-non-virtual-dtor was split into two groups back into https://reviews.llvm.org/D56405. but this change has not backported to llvm-toolset-7, which in turn packages Clang/LLVM 5.x.
to avoid the unknown warning options warning messages from the compiler when compiling the tree on el7, we need to check for the existence of this warning option before using it.
in this change,
* check for the existence of the "-Wdelete-non-abstract-non-virtual-dtor", before disabling it.
* only apply this option on C++ source files. as strictly speaking, this option only applies to C++.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
We thank you for helping improve Pipy. In order to ease the reviewing process, we invite you to read the …
> [build] check before adding -Wno-delete-non-abstract-non-virtual-dtor

- README.md
* Removed Katacoda link (Katacoda.com is sunset)
* Added Pipy Docker Desktop Extension installation link
> Updated README.md. Removed Katacoda and added Docker Extension Link

- .github/workflows/ci.yaml
As glibc may be  incompatible between  OS distributions, turn off static build flag for binary builds.
> [build] turn off static build flag for binary build

- rpm/pipy.spec
Add `perl-IPC-Cmd` as openssl3 requires it.
> [build] fix rpm dependency issue

- deps/zlib-1.3/CMakeLists.txt
- rpm/pipy.spec
Fix zlib compile issue and disable BPF on CentOS 7
Thanks for @naqvis's help.
> [build] fix for zlib and BPF issue on CentOS 7

- docs/getting-started/build-install.zh.mdx
Remove an unnecessary character in zh doc.
> Fix typo in zh doc

- Dockerfile
- build.sh
- multi_arch_images_build.sh
Current pipy version of docker image would should duplicate tag, e.g. `1.5.9-1.5.9`
```
Version          : 1.5.9-1.5.9
Commit           : ddd5f55915eaca575ac782c4a12c0e3110d3d5e2
Commit Date      : Mon, 13 Jan 2025 21:03:36 +0800
Host             : Linux-6.8.0-1017-azure x86_64
OpenSSL          : OpenSSL 3.2.0 23 Nov 2023
OpenSSL Conf     : /usr/local/ssl/openssl.cnf
Builtin GUI      : No
Builtin Codebases: No
```
This PR would remove the duplicate part.
> [ci] fix pipy version string in docker image

- CMakeLists.txt
Fix build dependency issue introduced in 786fb57a where switching to ExternalProject_Add for OpenSSL also removed the dependency declaration:
add_dependencies(pipy OpenSSL)
This caused build failures because pipy requires OpenSSL header files, including generated headers from OpenSSL's build process.
Solution: Create proper CMake OpenSSL library targets that depend on the OpenSSL build target. This ensures correct build ordering and allows linking against OpenSSL through CMake targets instead of raw library files.
We thank you for helping improve Pipy. In order to ease the reviewing process, we invite you to read the [guidelines](https://https://github.com/flomesh-io/pipy/blob/master/CONTRIBUTING.md#making-good-pull-requests) and ask you to consider the following points before submitting …
> [build] Export OpenSSL as proper CMake libraries

- docs/dts/Configuration.d.ts
- src/filters/tls.cpp
- src/filters/tls.hpp
Previously, when the `pqc` suboption was specified in acceptTLS() options, we would automatically assign default PQC algorithms for both key exchange and signature, even when only one was explicitly configured. This prevented users from mixing PQC and traditional algorithms.
Now we only apply PQC defaults to explicitly unspecified algorithms, allowing users to:
- Use PQC for key exchange with traditional signature algorithms
- Use traditional certificates while enabling PQC key exchange
- Have fine-grained control over which cryptographic operations use PQC
This change maintains backward compatibility while providing the flexibility to adopt PQC incrementally rather than requiring full PQC adoption.
We thank you for helping improve Pipy. In order to ease the reviewing process, we invite …
> [fix] PQC for both key exchange and signature algorithms
