flomesh-io/pipy

- Dockerfile
Copy test scripts to final image.
Temporarily disable set NET_ADMIN capability for pipy.
> Copy test scripts to final image.

- Dockerfile
- build.sh
Add building container image feature for build script;
Remove unnecessary vulnerable command jq from container image.
> Add building container image feature for build script

- README.md
- docs/overview.mdx
- docs/quick-start.mdx
- docs/tutorial/08-load-balancing-improved.mdx
- docs/tutorial/09-connection-pool.mdx
- docs/tutorial/17-body-transform.mdx
- docs/tutorial/18-tls.mdx
Added Tutorials:
* overview
* quick-start
* 09-connection-pool
* 17-body-transform
* 18-tls
Updated README
> added overview, quickstart, 09, 17, 18

- tutorial/19-load-balancing-advanced/config/balancer.json
- tutorial/19-load-balancing-advanced/config/proxy.json
- tutorial/19-load-balancing-advanced/config/router.json
- tutorial/19-load-balancing-advanced/plugins/balancer.js
- tutorial/19-load-balancing-advanced/plugins/default.js
- tutorial/19-load-balancing-advanced/plugins/router.js
- tutorial/19-load-balancing-advanced/proxy.js
1. support session sticky based on request user agent
2. support costomized load balance type for service. Use `RoundRobinLoadBalancer` by default if no type specified.
> add tutorial 19 load balancing advanced

- README.md
* Added Katacoda link
* Added InfoQ article link
> Added Learnings & Articles section in README

- README.md
- Removed **List Builtin Filters and Their Parameters** section as it has been removed from pipy executable.
> Removed List and help filters section

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Added 
* CODE OF CONDUCT
* Contributing
> Added Code of conduct and contributing document

- docs/quick-start.mdx
Update QuickStart, remove --list-filters description.
> [doc] Update QuickStart

- .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/feature-request.md
Added Github Issue templates for:
- Bug Report
- Discussion
- Feature Request
- Pull Request
> Added Issue templates for bug/discussion/feature/pr

- README_zh.md
> [docs] update README_zh

- README_jp.md
- docs/getting-started/getting-help.jp.mdx
> Add readme and getting-help docs in Japanese.

- docs/intro/concepts.zh.mdx
Update zh doc to align with en one.
> update stream part of concepts

- docs/intro/concepts.jp.mdx
> Modify concept in Japanese

- .github/workflows/ci.sh
- .github/workflows/ci.yaml
- .github/workflows/dockerfiles/Dockerfile
- rpm/Dockerfile
Setup github actions and provide following artifacts:
* x86 binary
* x86 rpm
* x86 alpine docker image
* aarch64 binary
* aarch64 alpine docker image
> [ci] setup github-actions

- Dockerfile
- build.sh
- rpm/Dockerfile
- rpm/pipy.spec
1. Revise build processes
2. Update alpine base image version to 3.14
3. Add option to choose whether use npm or not.
> [build] Revise build processes.

- .github/workflows/ci.yaml
- build.sh
* remove pjs from package name
* fix empty version info in binary package
> [ci] remove pjs from package name

- docs/reference/api/Configuration.mdx
- docs/reference/api/Configuration.zh.mdx
Updated Configuration.mdx with newly added filters.
> Updated Configuration document with new filters

- .github/workflows/ci.yaml
add pipy-repo image for x86 in release version
> [ci] add pipy-repo image for x86 in release version

- Dockerfile
- build.sh
- rpm/Dockerfile
- rpm/pipy.spec
As subject, support changing `CMAKE_BUILD_TYPE` to `Debug` in build.sh via cmd options `-d`
> [ci] support changing CMAKE_BUILD_TYPE to Debug in build.sh

- docs/tutorial/02-echo.zh.mdx
> Tiny fix in 02-echo

- docs/tutorial/04-routing.zh.mdx
> Modify 04-routing

- docs/tutorial/03-proxy.zh.mdx
- docs/tutorial/05-load-balancing.zh.mdx
> Modify 05-load-balancing

- docs/tutorial/06-configuration.zh.mdx
> Modify 06-configuration

- docs/tutorial/03-proxy.zh.mdx
- docs/tutorial/05-load-balancing.zh.mdx
> Update 03 and 05

- Dockerfile
- Dockerfile-loongnix
- rpm/pipy.spec
Now we use `PIPY_SAMPLES` instread of `PIPY_TUTORIAL`, change Dockerfile and rpm spec accordingly.
> [ci] change PIPY_TUTORIAL to PIPY_SAMPLES

- docs/reference/algo.js
- src/api/algo.cpp
- src/api/algo.hpp
Added optional parameter "produce" to algo.Quota.
> Added optional parameter "produce" to algo.Quota.

- docs/guides/07-plugins.mdx
- docs/guides/11-logging.mdx
- docs/intro/concepts.mdx
- docs/reference/Configuration.js
- docs/reference/api/Configuration/export.mdx
- docs/reference/api/Configuration/handleStreamStart.mdx
- docs/reference/api/Data/constructor.mdx
- docs/reference/api/Data/from.mdx
- docs/reference/api/Data/toString.mdx
- docs/reference/api/MessageEnd/tail.mdx
- docs/reference/pjs/1-language.mdx
- docs/tutorial/03-proxy.mdx
- docs/tutorial/04-routing.mdx
- docs/tutorial/05-load-balancing.mdx
- docs/tutorial/06-configuration.mdx
- docs/tutorial/07-plugins.mdx
- gui/src/components/doc-redirect.js
- src/api/configuration.cpp
- src/main-options.cpp
Signed-off-by: Loong <loong.dai@intel.com>
> fix some typos

- src/api/algo.cpp
Set a timer when the quota is not full.
> Set a timer when the quota is not full.

- src/filters/mqtt.cpp
Corrected the wrong parameter.
> Corrected the wrong parameter.

- package-lock.json
- package.json
Upgraded typescript version to "^4.8.4" from "^4.8.3"
> Chore - Upgraded typescript version

- .github/workflows/gui.yml
Try to build js code when relavant files change.
> [ci] add gui build check

- CMakeLists.txt
- src/api/dns.cpp
- src/api/dns.hpp
- src/worker.cpp
.replaceMessage(
&nbsp;   msg => (
&ensp;    new Message(DNS.decode(msg.body), null)
&nbsp;   )
)
.replaceMessage(
&nbsp;   msg => (
&ensp;    new Message(DNS.encode(msg.head))
&nbsp;  )
)
> Added DNS codec

- src/api/dns.cpp
[fix] Set/Get length of dns type TXT
> [fix] Set/Get length of dns type TXT

- .github/workflows/ci.yaml
* Upload artifacts to repo directly, avoid network issues
* Update some actions version
> [ci] upload artifacts to repo directly

- rpm/Dockerfile
- rpm/pipy.spec
> [ci]: do not install deps specified by .spec 

- .github/workflows/gui.yml
> [ci] fix node version

- src/filters/replay.cpp
> [Fixed] replay() not working.

- samples/bpf/packet-counter/Makefile
- samples/bpf/packet-counter/README.md
- samples/bpf/packet-counter/headers/bpf.h
- samples/bpf/packet-counter/headers/bpf_common.h
- samples/bpf/packet-counter/headers/bpf_debug.h
- samples/bpf/packet-counter/headers/bpf_endian.h
- samples/bpf/packet-counter/headers/bpf_helper_defs.h
- samples/bpf/packet-counter/headers/bpf_helpers.h
- samples/bpf/packet-counter/pkt_counter_kern.c
```bash
make kern
```
```bash
make demo-attach
```
```bash
make demo-test
```
```bash
make demo-map-dump
```
```bash
make demo-unattach
```
```bash
make clean
```
> add pkt counter demo.

- src/api/stats.cpp
Type annotations to Prometheus output available via `/metrics` endpoint
> Added type annotations to prometheus output

- CMakeLists.txt
- src/api/crypto.cpp
- src/filters/tls.cpp
- src/filters/tls.hpp
- src/main.cpp
This PR add support for compiling with Tongsuo, support NTLS and dual certification.
> feat: Added support for compiling with Tongsuo for NTLS

- docker-entrypoint.sh
Pipy has supported multi-threads mode for a long time, and update the `docker-entrypoint.sh` accordingly.
> [chore] use multi-threads mode instead of multi-processors mode

- README.md
- README_jp.md
- README_zh.md
-> Fix typo in README
2. Focus the PR to the …
> [chore] Fix typo in README

- .github/workflows/ci.yaml
- .github/workflows/gui.yml
- Dockerfile
- build.sh
* Bump some actions version
* Add macos and android packages when release
* Fix container image build without sample codebases issue
> Create draft release page when non-nightly version pushed

- multi_arch_images_build.sh
Create multi arch images build shell
2. Focus the …
> Create multi arch images build shell

- src/api/crypto.cpp
- src/api/crypto.hpp
- Add all ML-DSA signature algorithms (ML-DSA-44/65/87) to KeyType enum
- Add all SLH-DSA signature algorithms (SLH-DSA-128s/f, 192s/f, 256s/f) to KeyType enum
- Add all ML-KEM key exchange algorithms (ML-KEM-512/768/1024) to KeyType enum
- Implement PQC key generation in PrivateKey constructor using OpenSSL 3.5+ APIs
- Add PQC-aware certificate signing with proper digest handling for PQC algorithms
- Support both traditional RSA/DSA and new post-quantum cryptographic algorithms
- Enable JavaScript access to PQC key and certificate generation capabilities
We thank you for helping improve Pipy. In order to ease the reviewing process, we invite you to read the [guidelines](https://https://github.com/flomesh-io/pipy/blob/master/CONTRIBUTING.md#making-good-pull-requests) and ask you to …
> [feat] Add comprehensive PQC support to crypto module

- rpm/Dockerfile.centos8
Then we could build rpm for CentOS 8
```
DOCKERFILE=Dockerfile.centos8 ./build.sh -nr
```
> [ci] add Dockerfile for CentOS 8 rpm build
